# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@5.0.2



workflows:
  build:
    jobs:
      - node/test:
          filters:
            branches:
              only: circleci-project-setup

      - node/run:
          filters:
            branches:
              only: circleci-project-setup